c:
	gcc -O3 -o bubblesort-c-version bubblesort.c

cpp:
	g++ -O3 -o bubblesort-cpp-version bubblesort.cpp

golem:
	julia bubblesort-golem.jl

rosetta:
	julia bubblesort-rosetta.jl

optimized:
	julia bubblesort-julia-optimized.jl
